source 'https://rubygems.org'
gem 'rails', '3.2.12'

group :development do
  gem 'thin'
  gem 'powify'
  gem 'capistrano'
  gem 'capistrano_colors'
  gem 'rvm-capistrano'
  gem 'quiet_assets'
  gem 'pry-rails'
  gem 'awesome_print'
  gem 'quiet_assets'
  gem 'better_errors'
  gem 'binding_of_caller'
end

group :test do
  gem 'rspec-rails'
  gem 'factory_girl_rails'
  gem 'capybara'
  gem 'capybara-webkit'
  gem 'launchy'
  gem 'database_cleaner'
end

# Server
gem 'unicorn'
gem 'unicorn-worker-killer'
gem 'paperclip'
gem 'mongoid'
gem 'mongoid_token'
gem 'mongoid-tree'
gem 'mongoid-paperclip'
gem 'mongoid-slugify'
gem 'mongoid_rails_migrations'
gem 'babosa'
gem 'bson_ext'
gem 'json'
gem 'russian'
gem 'browser'

gem 'devise'
gem 'devise_invitable'
gem 'simple_form'
gem 'cancan'
gem 'omniauth'
gem 'omniauth-linkedin'
gem 'linkedin'

gem 'rails_admin'
gem 'ruby-graphviz'
gem 'crashlog'
gem 'postmark-rails'

# Client
gem 'less-rails'
gem 'coffee-rails'
gem 'uglifier'
gem 'execjs'
gem 'therubyracer'
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'i18n-js'
gem 'turbolinks'
gem 'turbolinks-analytics'
gem 'google-analytics-rails'
gem 'twitter-bootstrap-rails', '2.1.6'
gem 'mousetrap-rails'
gem 'underscore-rails'
gem 'lesselements-rails'#, github: 'krasnoukhov/lesselements-rails'
